-- Seed booking slots for the next 7 days
-- Time slots: 0900, 1000, 1100, 1400, 1500, 1600

INSERT INTO bookings (date, time, chat_id) VALUES
-- Day 1
(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '0900', NULL),
(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '1000', NULL),
(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '1100', NULL),
(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '1400', NULL),
(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '1500', NULL),
(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '1600', NULL),
-- Day 2
(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '0900', NULL),
(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '1000', NULL),
(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '1100', NULL),
(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '1400', NULL),
(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '1500', NULL),
(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '1600', NULL),
-- Day 3
(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '0900', NULL),
(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '1000', NULL),
(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '1100', NULL),
(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '1400', NULL),
(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '1500', NULL),
(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '1600', NULL),
-- Day 4
(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '0900', NULL),
(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '1000', NULL),
(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '1100', NULL),
(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '1400', NULL),
(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '1500', NULL),
(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '1600', NULL),
-- Day 5
(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '0900', NULL),
(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '1000', NULL),
(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '1100', NULL),
(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '1400', NULL),
(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '1500', NULL),
(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '1600', NULL),
-- Day 6
(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '0900', NULL),
(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '1000', NULL),
(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '1100', NULL),
(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '1400', NULL),
(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '1500', NULL),
(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '1600', NULL),
-- Day 7
(DATE_ADD(CURDATE(), INTERVAL 7 DAY), '0900', NULL),
(DATE_ADD(CURDATE(), INTERVAL 7 DAY), '1000', NULL),
(DATE_ADD(CURDATE(), INTERVAL 7 DAY), '1100', NULL),
(DATE_ADD(CURDATE(), INTERVAL 7 DAY), '1400', NULL),
(DATE_ADD(CURDATE(), INTERVAL 7 DAY), '1500', NULL),
(DATE_ADD(CURDATE(), INTERVAL 7 DAY), '1600', NULL)
ON DUPLICATE KEY UPDATE id=id;

